export const countries = [
  { code: "+1", name: "United States", flag: "🇺🇸" },
  { code: "+44", name: "United Kingdom", flag: "🇬🇧" },
  { code: "+91", name: "India", flag: "🇮🇳" },
  { code: "+86", name: "China", flag: "🇨🇳" },
  { code: "+81", name: "Japan", flag: "🇯🇵" },
  { code: "+49", name: "Germany", flag: "🇩🇪" },
  { code: "+33", name: "France", flag: "🇫🇷" },
  { code: "+39", name: "Italy", flag: "🇮🇹" },
  { code: "+34", name: "Spain", flag: "🇪🇸" },
  { code: "+52", name: "Mexico", flag: "🇲🇽" },
  { code: "+55", name: "Brazil", flag: "🇧🇷" },
  { code: "+61", name: "Australia", flag: "🇦🇺" },
  { code: "+82", name: "South Korea", flag: "🇰🇷" },
  { code: "+7", name: "Russia", flag: "🇷🇺" },
  { code: "+20", name: "Egypt", flag: "🇪🇬" },
  { code: "+27", name: "South Africa", flag: "🇿🇦" },
  { code: "+31", name: "Netherlands", flag: "🇳🇱" },
  { code: "+32", name: "Belgium", flag: "🇧🇪" },
  { code: "+41", name: "Switzerland", flag: "🇨🇭" },
  { code: "+43", name: "Austria", flag: "🇦🇹" },
  { code: "+45", name: "Denmark", flag: "🇩🇰" },
  { code: "+46", name: "Sweden", flag: "🇸🇪" },
  { code: "+47", name: "Norway", flag: "🇳🇴" },
  { code: "+48", name: "Poland", flag: "🇵🇱" },
  { code: "+351", name: "Portugal", flag: "🇵🇹" },
  { code: "+358", name: "Finland", flag: "🇫🇮" },
  { code: "+46", name: "Sweden", flag: "🇸🇪" },
  { code: "+65", name: "Singapore", flag: "🇸🇬" },
  { code: "+60", name: "Malaysia", flag: "🇲🇾" },
  { code: "+62", name: "Indonesia", flag: "🇮🇩" },
  { code: "+63", name: "Philippines", flag: "🇵🇭" },
  { code: "+66", name: "Thailand", flag: "🇹🇭" },
  { code: "+84", name: "Vietnam", flag: "🇻🇳" },
  { code: "+90", name: "Turkey", flag: "🇹🇷" },
  { code: "+92", name: "Pakistan", flag: "🇵🇰" },
  { code: "+94", name: "Sri Lanka", flag: "🇱🇰" },
  { code: "+98", name: "Iran", flag: "🇮🇷" },
  { code: "+966", name: "Saudi Arabia", flag: "🇸🇦" },
  { code: "+971", name: "United Arab Emirates", flag: "🇦🇪" },
  { code: "+972", name: "Israel", flag: "🇮🇱" },
  { code: "+212", name: "Morocco", flag: "🇲🇦" },
  { code: "+216", name: "Tunisia", flag: "🇹🇳" },
  { code: "+234", name: "Nigeria", flag: "🇳🇬" },
  { code: "+254", name: "Kenya", flag: "🇰🇪" },
  { code: "+251", name: "Ethiopia", flag: "🇪🇹" },
  { code: "+256", name: "Uganda", flag: "🇺🇬" },
  { code: "+233", name: "Ghana", flag: "🇬🇭" },
  { code: "+225", name: "Ivory Coast", flag: "🇨🇮" },
  { code: "+57", name: "Colombia", flag: "🇨🇴" },
  { code: "+54", name: "Argentina", flag: "🇦🇷" },
  { code: "+56", name: "Chile", flag: "🇨🇱" },
  { code: "+51", name: "Peru", flag: "🇵🇪" },
  { code: "+593", name: "Ecuador", flag: "🇪🇨" },
  { code: "+595", name: "Paraguay", flag: "🇵🇾" },
  { code: "+598", name: "Uruguay", flag: "🇺🇾" },
  { code: "+853", name: "Macau", flag: "🇲🇴" },
  { code: "+886", name: "Taiwan", flag: "🇹🇼" },
  { code: "+852", name: "Hong Kong", flag: "🇭🇰" },
  { code: "+80", name: "Bangladesh", flag: "🇧🇩" },
  { code: "+95", name: "Myanmar", flag: "🇲🇲" },
  { code: "+976", name: "Mongolia", flag: "🇲🇳" },
  { code: "+977", name: "Nepal", flag: "🇳🇵" },
  { code: "+880", name: "Bangladesh", flag: "🇧🇩" },
  { code: "+670", name: "East Timor", flag: "🇹🇱" },
  { code: "+856", name: "Laos", flag: "🇱🇦" },
  { code: "+855", name: "Cambodia", flag: "🇰🇭" },
  { code: "+95", name: "Myanmar", flag: "🇲🇲" },
  { code: "+964", name: "Iraq", flag: "🇮🇶" },
  { code: "+962", name: "Jordan", flag: "🇯🇴" },
  { code: "+961", name: "Lebanon", flag: "🇱🇧" },
  { code: "+968", name: "Oman", flag: "🇴🇲" },
  { code: "+973", name: "Bahrain", flag: "🇧🇭" },
  { code: "+974", name: "Qatar", flag: "🇶🇦" },
  { code: "+965", name: "Kuwait", flag: "🇰🇼" },
  { code: "+423", name: "Liechtenstein", flag: "🇱🇮" },
  { code: "+423", name: "Liechtenstein", flag: "🇱🇮" },
  { code: "+358", name: "Finland", flag: "🇫🇮" },
  { code: "+386", name: "Slovenia", flag: "🇸🇮" },
  { code: "+385", name: "Croatia", flag: "🇭🇷" },
  { code: "+387", name: "Bosnia", flag: "🇧🇦" },
  { code: "+381", name: "Serbia", flag: "🇷🇸" },
  { code: "+383", name: "Kosovo", flag: "🇽🇰" },
  { code: "+389", name: "North Macedonia", flag: "🇲🇰" },
  { code: "+355", name: "Albania", flag: "🇦🇱" },
  { code: "+382", name: "Montenegro", flag: "🇲🇪" },
  { code: "+373", name: "Moldova", flag: "🇲🇩" },
  { code: "+359", name: "Bulgaria", flag: "🇧🇬" },
  { code: "+40", name: "Romania", flag: "🇷🇴" },
  { code: "+36", name: "Hungary", flag: "🇭🇺" },
  { code: "+421", name: "Slovakia", flag: "🇸🇰" },
  { code: "+420", name: "Czech Republic", flag: "🇨🇿" },
  { code: "+370", name: "Lithuania", flag: "🇱🇹" },
  { code: "+371", name: "Latvia", flag: "🇱🇻" },
  { code: "+372", name: "Estonia", flag: "🇪🇪" },
  { code: "+356", name: "Malta", flag: "🇲🇹" },
  { code: "+357", name: "Cyprus", flag: "🇨🇾" },
  { code: "+353", name: "Ireland", flag: "🇮🇪" },
  { code: "+354", name: "Iceland", flag: "🇮🇸" },
  { code: "+376", name: "Andorra", flag: "🇦🇩" },
  { code: "+377", name: "Monaco", flag: "🇲🇨" },
  { code: "+378", name: "San Marino", flag: "🇸🇲" },
  { code: "+379", name: "Vatican", flag: "🇻🇦" },
  { code: "+501", name: "Belize", flag: "🇧🇿" },
  { code: "+502", name: "Guatemala", flag: "🇬🇹" },
  { code: "+503", name: "El Salvador", flag: "🇸🇻" },
  { code: "+504", name: "Honduras", flag: "🇭🇳" },
  { code: "+505", name: "Nicaragua", flag: "🇳🇮" },
  { code: "+506", name: "Costa Rica", flag: "🇨🇷" },
  { code: "+507", name: "Panama", flag: "🇵🇦" },
  { code: "+1", name: "Canada", flag: "🇨🇦" },
  { code: "+1", name: "Jamaica", flag: "🇯🇲" },
  { code: "+1", name: "Bahamas", flag: "🇧🇸" },
  { code: "+509", name: "Haiti", flag: "🇭🇹" },
  { code: "+1", name: "Dominican Republic", flag: "🇩🇴" },
  { code: "+1", name: "Puerto Rico", flag: "🇵🇷" },
  { code: "+1", name: "Trinidad", flag: "🇹🇹" },
  { code: "+592", name: "Guyana", flag: "🇬🇾" },
  { code: "+597", name: "Suriname", flag: "🇸🇷" },
];